Ingredients - 
1/2 cups (180 gr) all-purpose flour
1/2 cup (50 gr) cocoa powder (dutch processed preferred but natural cocoa powder can be used)
2/3 cup (130 gr) granulated sugar
1 TBSP (14 gr) baking powder
1/4 tsp salt
1 large egg, room temperature
1 cup (235 ml) whole milk
1 tsp vanilla extract
1/2 cup (120 ml) vegetable oil or canola oil
1 cup (170 gr) chocolate chips + more for topping if desired